# Generated by Django 2.2.5 on 2019-11-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Organización')),
                ('info', models.TextField(max_length=900, verbose_name='Descripción')),
                ('legalrep', models.CharField(max_length=100, verbose_name='Representantes')),
                ('number', models.CharField(max_length=100, verbose_name='Número de teléfono')),
            ],
            options={
                'verbose_name': 'Organización',
                'verbose_name_plural': 'Organizaciones',
            },
        ),
    ]
