# Generated by Django 2.2.5 on 2019-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='legalrep',
            field=models.CharField(max_length=100, verbose_name='Representante'),
        ),
    ]
