# Generated by Django 2.2.5 on 2019-11-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191127_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='clan',
            new_name='clan_id',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='person',
            new_name='user_id',
        ),
    ]
