# Generated by Django 2.2.5 on 2019-11-05 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address2',
        ),
    ]
