# Generated by Django 2.2.5 on 2019-09-30 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='WorldBorder',
        ),
    ]
