# Generated by Django 2.2.5 on 2019-11-05 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20191105_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='api.WorldBorder'),
        ),
    ]
