# Generated by Django 2.2.5 on 2019-10-09 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191009_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='tree_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree', to='api.Tree'),
        ),
    ]
