# Generated by Django 2.2.5 on 2019-11-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191105_0553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='tree',
            new_name='tree_id',
        ),
    ]
