# Generated by Django 2.2.5 on 2019-09-22 19:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_geoentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.AddField(
            model_name='country',
            name='area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='country',
            name='fips',
            field=models.CharField(default='XX', max_length=2, verbose_name='FIPS Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(default='XX', max_length=2, verbose_name='2 Digit ISO'),
        ),
        migrations.AddField(
            model_name='country',
            name='iso_3',
            field=models.CharField(default='XX', max_length=3, verbose_name='3 Digit ISO'),
        ),
        migrations.AddField(
            model_name='country',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='country',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.IntegerField(default=-1, verbose_name='Region Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.IntegerField(default=-1, verbose_name='Sub-Region Code'),
        ),
        migrations.AddField(
            model_name='country',
            name='un',
            field=models.IntegerField(default=-1, verbose_name='United Nations Code'),
        ),
    ]
