# Generated by Django 2.2.5 on 2019-10-09 23:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191009_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='shareholders',
            field=models.ManyToManyField(related_name='tree', through='api.Share', to=settings.AUTH_USER_MODEL),
        ),
    ]
