# Generated by Django 2.2.5 on 2019-09-22 21:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('api', '0004_auto_20190922_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='preferences', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('push_notifications_trees', models.BooleanField(default=True)),
                ('push_notifications_events', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Country'),
        ),
    ]
