# Generated by Django 2.2.5 on 2019-09-27 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190922_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='api.Country'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
