# Generated by Django 2.2.5 on 2019-10-09 23:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191009_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='share',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='share',
            name='tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tree'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='shareholders',
            field=models.ManyToManyField(through='api.Share', to=settings.AUTH_USER_MODEL),
        ),
    ]
