# Generated by Django 2.2.5 on 2019-11-07 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191105_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='treed_id',
            new_name='tree_id',
        ),
    ]
