# Generated by Django 2.2.5 on 2019-09-24 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20190924_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='shareholders',
            field=models.ManyToManyField(through='api.Share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share',
            name='tree_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tree'),
        ),
    ]
