# Generated by Django 2.2.5 on 2019-09-27 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190924_1838'),
        ('api', '0007_auto_20190924_2321'),
    ]

    operations = [
    ]
