# Generated by Django 2.2.5 on 2019-10-10 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='treed_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='api.Tree'),
        ),
    ]
