# Generated by Django 2.2.5 on 2019-10-10 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_photo_treed_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('D', 'Dañado'), ('P', 'Perdido'), ('NA', 'No Activo'), ('A', 'Activo')], default='NA', max_length=3)),
                ('string', models.CharField(default='x3tcS1', max_length=6)),
                ('tree_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indentifier', to='api.Tree')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
