# Generated by Django 2.2.5 on 2019-10-10 20:46

import api.models.Identifier
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='string',
            field=models.CharField(max_length=6),
        ),
    ]
