# Generated by Django 2.2.5 on 2019-10-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191010_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='string',
            field=models.CharField(max_length=6),
        ),
    ]
