# Generated by Django 2.2.5 on 2019-11-15 02:33

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='address',
            field=django_google_maps.fields.AddressField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tree',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100),
        ),
    ]
