# Generated by Django 2.2.5 on 2019-10-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_qrcode_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcode',
            name='id',
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='string',
            field=models.CharField(blank=True, max_length=6, primary_key=True, serialize=False),
        ),
    ]
