# Generated by Django 2.2.5 on 2019-11-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191114_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tree',
            name='geolocation',
        ),
    ]
