# Generated by Django 2.2.5 on 2019-11-15 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191115_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HasState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TreeState')),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Tree')),
            ],
        ),
        migrations.AddField(
            model_name='tree',
            name='states',
            field=models.ManyToManyField(through='api.HasState', to='api.TreeState'),
        ),
    ]
