# Generated by Django 2.2.5 on 2019-10-10 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191010_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='tree_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identifiers', to='api.Tree'),
        ),
    ]
