# Generated by Django 2.2.5 on 2019-10-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191010_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='id',
        ),
        migrations.AlterField(
            model_name='worldborder',
            name='iso2',
            field=models.CharField(default='XX', max_length=2, primary_key=True, serialize=False, verbose_name='2 Digit ISO'),
        ),
    ]
