# Generated by Django 2.2.5 on 2019-11-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191115_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hasstate',
            options={'verbose_name': 'estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='treestate',
            options={'verbose_name': 'estado', 'verbose_name_plural': 'Estados'},
        ),
    ]
