# Generated by Django 2.2.5 on 2019-10-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20191020_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worldborder',
            old_name='iso_3',
            new_name='iso3',
        ),
    ]
