# Generated by Django 2.2.5 on 2019-10-20 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191020_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worldborder',
            name='location',
        ),
    ]
