# Generated by Django 2.2.5 on 2019-11-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateTimeField(default='2019-10-10i'),
            preserve_default=False,
        ),
    ]
