# Generated by Django 2.2.5 on 2019-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.ImageField(default='test', upload_to='events'),
            preserve_default=False,
        ),
    ]
