# Generated by Django 2.2.5 on 2019-11-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_event_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='final_date',
        ),
        migrations.AddField(
            model_name='event',
            name='initial_date',
            field=models.DateTimeField(default='2018-11-21'),
            preserve_default=False,
        ),
    ]
