# Generated by Django 2.2.5 on 2019-11-25 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0022_auto_20191122_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='treestate',
            options={'verbose_name': 'estado', 'verbose_name_plural': 'Estados catálogo'},
        ),
        migrations.AlterField(
            model_name='tree',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='specie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TreeSpecie', verbose_name='Especie'),
        ),
        migrations.CreateModel(
            name='AchievementCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='trees')),
                ('achievement', models.ManyToManyField(through='api.Achievement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'logro',
                'verbose_name_plural': 'Catalogo de  Logros',
            },
        ),
        migrations.AddField(
            model_name='achievement',
            name='achievement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameA', to='api.AchievementCatalog'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL),
        ),
    ]
