# Generated by Django 2.2.5 on 2019-11-23 16:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191123_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='dateCreated',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
