# Generated by Django 2.2.5 on 2019-11-25 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20191125_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='achievement_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nameA', to='api.AchievementCatalog', verbose_name='Logro'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
