# Generated by Django 2.2.5 on 2019-11-25 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191125_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'logro', 'verbose_name_plural': 'Logros'},
        ),
    ]
