# Generated by Django 2.2.5 on 2019-11-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20191123_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tip', models.CharField(max_length=255)),
                ('tree_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.TreeSpecie')),
            ],
        ),
    ]
