# Generated by Django 2.2.5 on 2019-11-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_treetip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treetip',
            name='tip',
            field=models.TextField(max_length=255),
        ),
    ]
