# Generated by Django 2.2.5 on 2019-11-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20191123_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treetip',
            name='tree_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='api.TreeSpecie'),
        ),
    ]
