# Generated by Django 2.2.5 on 2019-11-25 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('social_django', '0008_partial_timestamp'),
        ('api', '0029_auto_20191125_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
