# Generated by Django 2.2.5 on 2019-11-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_post_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
