# Generated by Django 2.2.5 on 2019-11-26 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20191125_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tree',
            options={'verbose_name': 'árbol de usuario', 'verbose_name_plural': 'Árboles de usuarios'},
        ),
    ]
