# Generated by Django 2.2.5 on 2019-11-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20191126_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0, verbose_name='Edad')),
                ('specie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.TreeSpecie', verbose_name='Especie')),
            ],
            options={
                'verbose_name': 'árbol de inverdana',
                'verbose_name_plural': 'Árboles de Inverdana',
            },
        ),
    ]
