# Generated by Django 2.2.5 on 2019-11-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'árbol', 'verbose_name_plural': 'Árboles de Inverdana (Inventario)'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
