# Generated by Django 2.2.5 on 2019-11-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20191126_0130'),
        ('api', '0027_auto_20191123_1919'),
        ('api', '0025_auto_20191125_1548'),
    ]

    operations = [
    ]
