# Generated by Django 2.2.5 on 2019-11-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20191126_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='age',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='stock',
            name='desc',
            field=models.TextField(default='test', max_length=100, verbose_name='Descripción'),
            preserve_default=False,
        ),
    ]
