# Generated by Django 2.2.5 on 2019-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20191126_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(null=True, upload_to='users'),
        ),
    ]
