# Generated by Django 2.2.5 on 2019-11-27 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_contact_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tree',
            old_name='states',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='hasstate',
            name='tree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='states', to='api.Tree'),
        ),
    ]
