# Generated by Django 2.2.5 on 2019-11-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20191127_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasstate',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='hasstate',
            name='photo',
            field=models.ImageField(null=True, upload_to='reports'),
        ),
        migrations.AlterField(
            model_name='hasstate',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
