# Generated by Django 2.2.5 on 2019-12-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20191127_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Precio')),
            ],
            options={
                'verbose_name_plural': 'Árboles de navidad',
                'verbose_name': 'árbol de navidad',
            },
        ),
        migrations.CreateModel(
            name='PineSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Tamaño')),
            ],
            options={
                'verbose_name_plural': 'Tamaños',
                'verbose_name': 'tamaño',
            },
        ),
        migrations.CreateModel(
            name='PineSpecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commonname', models.CharField(max_length=100)),
                ('sciname', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Especies de árboles',
                'verbose_name': 'especie de árbol',
            },
        ),
        migrations.CreateModel(
            name='PineState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Estados catálogo',
                'verbose_name': 'estado',
            },
        ),
        migrations.AlterModelOptions(
            name='preference',
            options={'verbose_name': 'Preferencia', 'verbose_name_plural': 'Preferencias de usuario'},
        ),
        migrations.AlterModelOptions(
            name='treetip',
            options={'verbose_name': 'tip', 'verbose_name_plural': 'Tips de árboles'},
        ),
    ]
