# Generated by Django 2.2.5 on 2019-12-04 20:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0045_auto_20191204_1343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pineprice',
            options={'verbose_name': 'tamaño', 'verbose_name_plural': 'Tamaños'},
        ),
        migrations.RemoveField(
            model_name='pinespecie',
            name='commonname',
        ),
        migrations.AddField(
            model_name='pinespecie',
            name='specie_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pineprice',
            name='price',
            field=models.IntegerField(default=0, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='pinestate',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PineTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=100)),
                ('photo', models.ImageField(null=True, upload_to='christmas')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PinePrice', verbose_name='Precio')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PineSize', verbose_name='Tamaño')),
                ('specie_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PineSpecie', verbose_name='Especie')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PineState', verbose_name='Estado')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Árboles de navidad',
                'verbose_name': 'árbol de navidad',
            },
        ),
    ]
