# Generated by Django 2.2.5 on 2019-12-06 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0046_auto_20191204_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='PineLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(max_length=100)),
                ('price', models.IntegerField(null=True, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
        migrations.AlterModelOptions(
            name='pinetree',
            options={},
        ),
        migrations.RemoveField(
            model_name='pinetree',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pinetree',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='pinetree',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pinetree',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='PinePrice',
        ),
        migrations.AddField(
            model_name='pineloan',
            name='tree_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PineTree', verbose_name='Arbol'),
        ),
        migrations.AddField(
            model_name='pineloan',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
