# Generated by Django 2.2.5 on 2019-12-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20191206_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinesize',
            options={'verbose_name': 'tamaño', 'verbose_name_plural': 'Tamaños de árboles de navidad'},
        ),
        migrations.AlterModelOptions(
            name='pinespecie',
            options={'verbose_name': 'especie de árbol de navidad', 'verbose_name_plural': 'Especies de árboles de navidad'},
        ),
        migrations.AlterModelOptions(
            name='pinestate',
            options={'verbose_name': 'estado del árbol de navidad', 'verbose_name_plural': 'Estados de árboles de navidad'},
        ),
        migrations.AlterModelOptions(
            name='pinetree',
            options={'verbose_name': 'árbol de navidad', 'verbose_name_plural': 'Árboles de Navidad'},
        ),
        migrations.AlterField(
            model_name='pinespecie',
            name='sciname',
            field=models.CharField(max_length=100, verbose_name='nombre científico'),
        ),
        migrations.AlterField(
            model_name='pinespecie',
            name='specie_id',
            field=models.CharField(max_length=100, null=True, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='pinestate',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='estatus del árbol'),
        ),
    ]
